version: "3"

services:
  coturn:
    build: .
    container_name: coturn
    environment:
      USERNAME: username # For example, only
      PASSWORD: password # For example, only
      REALM: realm # For example, only
    # ports:
    #  - 3478:3478
    #  - 3478:3478/udp
    #  - 65435-65535:65435-65535/udp
    network_mode: host # Expose directly on the host
